### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by chnouman** [Kaljurand/speechutils#10]
At least provide a simple example code to understand how to start the recorder and get results from it in String format.

**Comment by Kaljurand** [comment]
Closing as already covered by https://github.com/Kaljurand/speechutils/issues/8

**Comment by chnouman** [comment]
@Kaljurand is there any Speech to Text feature available in this repo or it just providing audio for services that do STT?

**Comment by Kaljurand** [comment]
It offers some audio recording/compression functionality and access to STT services that are installed on the device. It does not contain any service implementations, but in the future some might be migrated here from https://github.com/Kaljurand/K6nele

**Comment by chnouman** [comment]
@Kaljurand ok Thank you for your response.
